spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
server:
  port: 8084
#service:
#  host: http://localhost:8080
#  allocation: /Allocation/
#    findAll: fetchAllAllocations
#    findByEmpId: findAllocationByEmpId
